/**
 * Tập trung tất cả permission codes từ backend.
 * Dùng các hằng này thay cho string literal để tránh typo.
 */
export const P = {
  // ── SYSTEM ──────────────────────────────────────
  DASHBOARD_VIEW:     "DASHBOARD_VIEW",
  ACTIVITY_LOG_VIEW:  "ACTIVITY_LOG_VIEW",

  // ── REPORT ──────────────────────────────────────
  REPORT_REVENUE_VIEW:   "REPORT_REVENUE_VIEW",
  REPORT_INVENTORY_VIEW: "REPORT_INVENTORY_VIEW",
  REPORT_INVENTORY_VIEW_ALL_BRANCHES: "REPORT_INVENTORY_VIEW_ALL_BRANCHES",
  REPORT_FINANCE_VIEW:   "REPORT_FINANCE_VIEW",
  REPORT_FINANCE_VIEW_ALL_BRANCHES: "REPORT_FINANCE_VIEW_ALL_BRANCHES",

  // ── ADMINISTRATION ───────────────────────────────
  STAFF_VIEW:   "STAFF_VIEW",
  STAFF_CREATE: "STAFF_CREATE",
  STAFF_UPDATE: "STAFF_UPDATE",
  STAFF_DELETE: "STAFF_DELETE",

  BRANCH_VIEW:   "BRANCH_VIEW",
  BRANCH_CREATE: "BRANCH_CREATE",
  BRANCH_UPDATE: "BRANCH_UPDATE",
  BRANCH_DELETE: "BRANCH_DELETE",

  ROLE_VIEW:   "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",

  // ── SALES ────────────────────────────────────────
  ORDER_VIEW:     "ORDER_VIEW",
  ORDER_CREATE:   "ORDER_CREATE",
  ORDER_UPDATE:   "ORDER_UPDATE",
  ORDER_CONFIRM:  "ORDER_CONFIRM",
  ORDER_SHIP:     "ORDER_SHIP",
  ORDER_CANCEL:   "ORDER_CANCEL",
  ORDER_COMPLETE: "ORDER_COMPLETE",
  ORDER_EXPORT:   "ORDER_EXPORT",
  ORDER_REFUND:   "ORDER_REFUND",
  ORDER_DELETE:   "ORDER_DELETE",

  CUSTOMER_VIEW:   "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  VOUCHER_VIEW:   "VOUCHER_VIEW",
  VOUCHER_CREATE: "VOUCHER_CREATE",
  VOUCHER_UPDATE: "VOUCHER_UPDATE",
  VOUCHER_DELETE: "VOUCHER_DELETE",

  // ── PRODUCT_CATALOG ─────────────────────────────
  PRODUCT_VIEW:   "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  CATEGORY_VIEW:   "CATEGORY_VIEW",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  ATTRIBUTE_VIEW:   "ATTRIBUTE_VIEW",
  ATTRIBUTE_CREATE: "ATTRIBUTE_CREATE",
  ATTRIBUTE_UPDATE: "ATTRIBUTE_UPDATE",
  ATTRIBUTE_DELETE: "ATTRIBUTE_DELETE",

  // ── INVENTORY ────────────────────────────────────
  SUPPLIER_VIEW:   "SUPPLIER_VIEW",
  SUPPLIER_CREATE: "SUPPLIER_CREATE",
  SUPPLIER_UPDATE: "SUPPLIER_UPDATE",
  SUPPLIER_DELETE: "SUPPLIER_DELETE",

  DRIVER_VIEW:     "DRIVER_VIEW",
  DRIVER_CREATE:   "DRIVER_CREATE",
  DRIVER_UPDATE:   "DRIVER_UPDATE",
  DRIVER_DELETE:   "DRIVER_DELETE",

  IMPORT_VIEW:    "IMPORT_VIEW",
  IMPORT_CREATE:  "IMPORT_CREATE",
  IMPORT_UPDATE:  "IMPORT_UPDATE",
  IMPORT_APPROVE: "IMPORT_APPROVE",
  IMPORT_CANCEL:  "IMPORT_CANCEL",
  IMPORT_DELETE:  "IMPORT_DELETE",

  EXPORT_VIEW:    "EXPORT_VIEW",
  EXPORT_CREATE:  "EXPORT_CREATE",
  EXPORT_APPROVE: "EXPORT_APPROVE",
  EXPORT_UPDATE:  "EXPORT_UPDATE",
  EXPORT_CANCEL:  "EXPORT_CANCEL",
  EXPORT_DELETE:  "EXPORT_DELETE",

  TRANSFER_VIEW:    "TRANSFER_VIEW",
  TRANSFER_CREATE:  "TRANSFER_CREATE",
  TRANSFER_APPROVE: "TRANSFER_APPROVE",
  TRANSFER_CANCEL:  "TRANSFER_CANCEL",
  TRANSFER_DELETE:  "TRANSFER_DELETE",
  TRANSFER_UPDATE:  "TRANSFER_UPDATE",

  INVENTORY_CHECK_VIEW:    "INVENTORY_CHECK_VIEW",
  INVENTORY_CHECK_CREATE:  "INVENTORY_CHECK_CREATE",
  INVENTORY_CHECK_UPDATE:  "INVENTORY_CHECK_UPDATE",
  INVENTORY_CHECK_DELETE:  "INVENTORY_CHECK_DELETE",
  INVENTORY_CHECK_APPROVE: "INVENTORY_CHECK_APPROVE",
  INVENTORY_CHECK_CANCEL:  "INVENTORY_CHECK_CANCEL",

  // Legacy aliases
  CHECK_VIEW:    "INVENTORY_CHECK_VIEW",
  CHECK_CREATE:  "INVENTORY_CHECK_CREATE",
  CHECK_UPDATE:  "INVENTORY_CHECK_UPDATE",
  CHECK_DELETE:  "INVENTORY_CHECK_DELETE",
  CHECK_APPROVE: "INVENTORY_CHECK_APPROVE",
  CHECK_CANCEL:  "INVENTORY_CHECK_CANCEL",

  // ── PURCHASE REQUEST (Phiếu yêu cầu mua NCC) ─────
  PURCHASE_REQUEST_VIEW:    "PURCHASE_REQUEST_VIEW",
  PURCHASE_REQUEST_CREATE:  "PURCHASE_REQUEST_CREATE",
  PURCHASE_REQUEST_UPDATE:  "PURCHASE_REQUEST_UPDATE",
  PURCHASE_REQUEST_APPROVE: "PURCHASE_REQUEST_APPROVE",
  PURCHASE_REQUEST_DELETE:  "PURCHASE_REQUEST_DELETE",

  // ── MARKETING CONTENT ────────────────────────────
  BANNER_VIEW:   "BANNER_VIEW",
  BANNER_CREATE: "BANNER_CREATE",
  BANNER_EDIT:   "BANNER_EDIT",
  BANNER_DELETE: "BANNER_DELETE",

  BLOG_VIEW:    "BLOG_VIEW",
  BLOG_CREATE:  "BLOG_CREATE",
  BLOG_EDIT:    "BLOG_EDIT",
  BLOG_DELETE:  "BLOG_DELETE",
  BLOG_APPROVE: "BLOG_APPROVE",

  // ── SETTING ──────────────────────────────────────
  SETTING_VIEW:   "SETTING_VIEW",
  SETTING_UPDATE: "SETTING_UPDATE",

  // ── COMMUNICATION ────────────────────────────────
  CUSTOMER_ADVISOR_USE: "CUSTOMER_ADVISOR_USE",
  CHAT_VIEW:   "CHAT_VIEW",
  CHAT_MANAGE: "CHAT_MANAGE",

  // ── AI KNOWLEDGE / AGRONOMIST ───────────────────
  AGRONOMIST_WORKSPACE_USE: "AGRONOMIST_WORKSPACE_USE",
  AI_KNOWLEDGE_VIEW: "AI_KNOWLEDGE_VIEW",
  AI_KNOWLEDGE_CREATE: "AI_KNOWLEDGE_CREATE",
  AI_KNOWLEDGE_UPDATE: "AI_KNOWLEDGE_UPDATE",
  AI_KNOWLEDGE_APPROVE: "AI_KNOWLEDGE_APPROVE",
  AI_IMPORT_KNOWLEDGE: "AI_IMPORT_KNOWLEDGE",
  AI_CASE_REVIEW: "AI_CASE_REVIEW",
} as const;

export type PermissionCode = (typeof P)[keyof typeof P];
